# h2
spring:
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  profiles:
    active: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect