# h2
spring:
  h2:
    console:
      enabled: true
      path: /h2

# Datasource
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
